# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#http://www.finalconcept.com.au/article/view/symfony-routing-sfdoctrineroute
book_list:  
  url:      /book/list  
  param:    { module: book, action: list }  
book_view:  
  url:      /book/view/:author/:title  
  param:    { module: book, action: view }  
  class:    sfDoctrineRoute  
  options:  { model: Book, type: object }  
book_show:
  url:    /:module/:action/:id
  param:    { module: book, action: show }  

#job_search:
#  url:   /search
#  param: { module: job, action: search }
job_search:
  url:   /search.:sf_format
  param: { module: job, action: search, sf_format: html }
  requirements:
    sf_format: (?:html|js)

job_show_user:
  url:   /job/:company_slug/:location_slug/:id/:position_slug
  param: { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [get]
  class:   sfDoctrineRoute
  options:
    model: JobeetJob 
    type: object
    #Instead of displaying the job, we need to forward the user to a 404 page.
    method_for_query: retrieveActiveJob

category:
  url:     /category/:slug.:sf_format
  class:   sfDoctrineRoute
  param:   { module: category, action: show, sf_format: html }
  options: { model: JobeetCategory, type: object }
  requirements:
    sf_format: (?:html|atom)

job:
  class:   sfDoctrineRouteCollection
  options:
    model:          JobeetJob
    column:         token
    object_actions: { publish: PUT, extend: PUT }
  requirements:
    token: \w+

api_jobs:
  url:     /api/:token/jobs.:sf_format
  class:   sfDoctrineRoute
  param:   { module: api, action: list }
  options: { model: JobeetJob, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)

# default rules
homepage:
  url:   /
  param: { module: job, action: index }
  #param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
affiliate:
  class:   sfDoctrineRouteCollection
  options:
    model: JobeetAffiliate
    actions: [new, create]
    object_actions: { wait: get }

#./lib/vendor/symfony/data/bin/symfony
#svn propedit svn:ignore .

